version: '3'

services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
        MYSQL_USER: admin
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_PASSWORD: 123456

  redis:
    image: redis/redis-stack
    ports:
      - '8001:8001'
      - '6379:6379'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATA_BASE: payment
